### ISSUE TITLE
Download and clean data

### ISSUE THREAD

**Issue by nadialucas** [nadialucas/maya_epic_task#1]
To start this data project, I would like for you to download some data. To do this, complete the following steps:
1. Using the Python module, I would like you to download all the data from [this webpage](http://www.jasmiths.com/data_project). 
2. From there, use Stata (or your language of choice) to combine all of the data files. 
3.  Create a `statefips` variable, which is comprised of the first two digits of `fips`. This `statefips` variable corresponds to the [ANSI's codes](https://www.census.gov/geo/reference/ansi_statetables.html) for classifying states.
4.  Save this file as `superfund_sample`

**Comment by manorman5** [comment]
I finished here's the link: https://github.com/nadialucas/maya_epic_task/commit/883495c5404095ae675cd1e2ba26aa5664480011
